load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "event_and_message",
    srcs = [],
    hdrs = ["event_and_message.h"],
    deps = [
        "//Reactor/Proto/Event/Base:event_cc_proto",
        "@com_google_absl//absl/memory",
    ],
)
