package(default_visibility = ["//visibility:public"])

java_library(
    name = "event_and_message",
    srcs = ["EventAndMessage.java"],
    deps = [
        "@com_google_protobuf//:protobuf_java",
        "//Reactor/Proto/Event/Base:event_java_proto",
    ],
)
