package(default_visibility = ["//visibility:public"])

java_binary(
    name = "Convert",
    srcs = ["Convert.java"],
    data = [
        "//Example/Strings:convert",
    ],
    deps = [
        "//Example/Strings:convert",
    ],
)
